id = "axe"
name = "Axe Accessibility Linter"
version = "0.0.1"
schema_version = 1
authors = ["Taylor Plewe <tplewe@outlook.com>"]
description = "Acts as the client for an already-provided axe Accessibility Linter server executable"
repository = "https://github.com/taylorplewe/zed-axe-linter"

[language_servers.axe]
name = "Axe Accessibility Linter"
languages = ["HTML", "Vue.js"]
